### ISSUE TITLE
Backend repository is either private or does not exist

### ISSUE THREAD

**Issue by dwi4122** [TharunKumarrA/FC-TeamForge#21]
Cloning the backend repo, results in these results.

Cloning into 'FC-TeamForge-Backend'...
remote: Repository not found.
fatal: repository 'https://github.com/Thanus-Kumarr/FC-TeamForge-Backend.git/' not found

**Comment by TharunKumarrA** [comment]
Ohh sorry there was a typo while writing the Readme. Will fix and give thr correct repo asap

**Comment by TharunKumarrA** [comment]
https://github.com/Thanus-Kumaar/FC-TeamForge-server

This is the repo ...
